### PR TITLE
added year_num() function: process from R-Instat to extract year from a date

### PR DESCRIPTION
**Pull request by dannyparsons**
- added `date_components.py` file containing a single function `year_num()` following a similar structure to [climatol windrose()](https://github.com/opencdms/pyopencdms/blob/main/opencdms/process/climatol/__init__.py) to call R script and retrieve output
- added `yday_366.r` containing an R function required by `year_num()`

@iedwards some general questions arising from this PR:

- What is the correct folder and file structure for the processes to be created? e.g. a folder for each process, or each group like R-Instat,? Should files contain a single function?
- Should we be using a documentation convention such as docstrings to document Python functions created?
- In what format will data be passed in to processes? e.g. `obs` for `windrose()` or `dates` for `year_num()`. Will the processes need to deal with multiple formats or will this be standardised?
- In what format should functions that return data be in? Here I have used `np.array` to return a numeric array of years.
- There seems to be multiple ways of using the `rpy2` package to interact with R. For example, I used a different way of converting a Python array into an R compatible array than used in [climatol windrose()](https://github.com/opencdms/pyopencdms/blob/main/opencdms/process/climatol/__init__.py#L24)

Happy to make separate issues for these questions to allow discussion.

### CODE REVIEW

**Comment by isedwards** [comment]
Do we want to expose functions like `year_num()`?

I had expected this level of function to remain hidden, perhaps inside an R-instat CRAN library, and that only the process names that we identified in the process catalog would be made available in this intial phase?

**Comment by dannyparsons** [comment]
Yes, possibly this is not useful to expose. I picked this from the R-Instat processes list as one that I thought was simple to implement to start understanding `rpy2` and how to implement generally. I could pick a more obvious useful one instead like a graphical display.

**Comment by isedwards** [comment]
Apologies Danny - I didn't remember that "make dates from components" and "use dates" (to return the component parts) were top priorities on the R-Instat process list.

This is a capability that is likely to be required when importing, exporting and cleaning data and will also feed into other processes.

I'll take another look at it in this context. It raises some interesting questions.

**Comment by dannyparsons** [comment]
Yes, that makes sense. It wasn't clear to me how this might be used directly but it could be useful as a data processing step for other processes as you mention.

If you could also comment on the general approach that would be useful as I could then start on some of the graphical processes.

**Comment by isedwards** [comment]
Is there an obvious process (or processes) that could use the date components that we can do next and use as a demonstration?

**Comment by dannyparsons** [comment]
There are some R-Instat processes that require date components, for example, the climatic boxplots process requires year and "day of year" components from the date. If we assume that the climatic boxplot process will have a single "date" argument then it could use the internal date component methods internally. Is that the kind of thing you were thinking? If so, I could add that process to the PR.

**Comment by Steve-Palmer** [comment]
I think the aim here is to enable a dialogue to set up the required dates and times and to pass them into the database in the right format. Climsoft uses a datetime data type, but other databases will use other formats, especially the CLICOM CSV files which are numeric text fields. So this is a sub-process which will be needed by a lot of other processes. It might be as simple as defining in the API interface that the argument must be a datetime type value or range, and then for those databases which always use a datetime, then the action is null, but for others it would translate the datetime into text or numbers. There is a linked issue about the exact definition of the datetime attached to an observation, especially for values over a period (rainfall, max and min temperature etc). Midas and Climsoft define these as the time of observation, with the period extending backwards from that time. CLICOM used the traditional "cast-back" date for daily rainfall and max temperature, but not min temperature. WIGOS metadata allows for multiple definitions including the start of period and mid-period.

**Comment by dannyparsons** [comment]
Yes, I think these might be lower level processes to handle dates/times from and into databases. There's also a question of whether these should be implemented via R as they could also be done easily in Python.

My intention here was mainly to create an example of an R-Instat process implemented in this structure, but I recognise this wasn't the best starting point as date/times has broader points to consider. I think a graphical process might be a simpler starting point.

**Comment by isedwards** [comment]
@dannyparsons I actually think we're on the right track here.

Yes, date management in the database will be more complicated and we'll need to create similar capabilities in Python in the future, but if we continue as we are we have the opportunity to achieve:
a) three or more externally-identified high-priority R-Instat processes implemented
b) a demonstration of process chaining
c) conformance with our principle of working with external libraries (e.g. R-Instat) without modifying them to suit OpenCDMS, e.g. using date components to give boxplots the input it expects

**Comment by dannyparsons** [comment]
Ok I'll continue on this to implement the climatic boxplots functionality as well using the date components aspects.

How do you see process chaining working? One implementation of climatic boxplots would be calling the date components within the method e.g.
``` python
def climatic_boxplots(date, ...) # + other parameters for boxplot
   # call date component processes
   year <- year_num(date)
   doy <- doy(date)
   # call R code to produce boxplots
```
But this isn't chaining the processes, just calling them within each other.

In R you could do something like below where `df` is a data frame with `date` and `rain` columns. This is 'piped' to the `mutate()` function to manipulate the data by adding `year` and `doy` columns and then the result with the new columns is piped to `ggplot` to produce the graph. (`mutate` is part of the `dplyr` package's "grammar of data manipulation")
```r
df %>% 
   mutate(year = year_num(date), doy = doy(date)) %>% 
   ggplot(aes(x = doy, y = rain)) + 
      geom_boxplot() +
      facet_wrap(~year)
```

In Python we could achieve something similar by adopting the [pandas package](https://pandas.pydata.org/) for working with data and any one of the data manipulation packages that replicate dplyr's piping ([dplython](https://github.com/dodger487/dplython), [plydata](https://github.com/has2k1/plydata), [pandas-ply](https://github.com/coursera/pandas-ply)). Maybe something like:
``` python
def climatic_boxplots(data, ...) # + other parmaters for boxplot
   data >> mutate(year = year_num(X.date), doy = doy(X.date)) >> boxplots(x = "doy", y = "rain", facet = "year")
```

Is this the kind of thing you were thinking of or not?

**Comment by isedwards** [comment]
Piping the output of one function to the input to the next function isn't standard in Python - it's probable best that we don't force developers to use it (but it looks interesting, and could be useful).

By "chaining" I just mean two separate functions that can be called sequentially.
1. In the Python environment I'm using "chaining" in the context of a function chain (due to our grammar conversations - see image below):
```
new_obs = add_date_components(obs)
plot = boxplot(new_obs, ...)
```
- It could be combined in a single statement, but it's not necessary: `boxplot(add_date_components(obs), ...)`
- My example may be contrived... `new_obs` may actually be the same object as `obs`.

2. In the Web API context I mean "process chaining". I'm having trouble finding a simple example, but [see here](https://docs.geoserver.org/stable/en/user/services/wps/processes/chaining.html)

---

We already have pandas as a [pyopencdms dependency](https://github.com/opencdms/pyopencdms/blob/main/requirements.txt)... could you return a pandas' DataFrame instead of a numpy array?

GG Function chain

**Comment by jaggh** [comment]
Most of you already know (sorry!), but here is a reminder of plain R ways to extract components from a date. Example:
date=as.Date('2020-04-17') #create a date
strftime(date,'%Y') #year
strftime(date,'%m') #month
strftime(date,'%d') #day
strftime(date,'%j') #day of the year ('julian' day)

**Pull request merged**
